### ISSUE TITLE
User下的index.test.ts测试文件测试失败

### ISSUE THREAD

**Issue by rocky-191** [haixiangyan/jest-tutorial-example#1]
报错Unexpected token `,`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, `
      │ for template literal, (, or an identifier

代码和仓库里的一模一样
![image](https://user-images.githubusercontent.com/13551340/171970187-6d23cf3c-1c71-4751-a3a9-e2cfe29fa298.png)
![image](https://user-images.githubusercontent.com/13551340/171970202-2826d67e-3c8b-444a-bd99-e18dc278bc2f.png)

**Comment by haixiangyan** [comment]
推个你的仓库看看

**Comment by rocky-191** [comment]
> 推个你的仓库看看
https://github.com/rocky-191/learn-jest

**Comment by haixiangyan** [comment]
1. 把 `index.test.ts` 改成 `index.test.tsx`
2. 把 `store/selector.ts` 改成 `store/selectors.ts`
3. 把 `store/thunk.ts` 改成 `store/thunks.ts`

**Comment by rocky-191** [comment]
> 1. 把 `index.test.ts` 改成 `index.test.tsx`
> 2. 把 `store/selector.ts` 改成 `store/selectors.ts`
> 3. 把 `store/thunk.ts` 改成 `store/thunks.ts`

大意了，多谢
