### ISSUE TITLE
跟着教程走到 `引入 React（纯配置）`这一章节，配置好后启动`webpack`报错

### ISSUE THREAD

**Issue by GOWxx** [haixiangyan/jest-tutorial-example#2]
从开始的章节一直到`引入 React（纯配置）`这一章节，按文章内容配置
启动项目会报错，在 win10 和 apple m1 monterey 复现
复现demo: https://github.com/GOWxx/jest-study-example-for-gowxx/tree/repro/webpack_react
在此项目此分支`repro/webpack_react`下载代码
运行命令
`npm install`
`npm run start`
即可看见报错, 报错如下

![image](https://user-images.githubusercontent.com/12870715/173304526-f8b6e9d5-d7b7-4b95-9317-1d6c12472b7a.png)

直接拿配套项目
https://github.com/haixiangyan/jest-tutorial-example
的 `package.json` 替换都不行，还需要替换 `package-lock.json` 然后删除 `node_modules` 重新安装，才能正常运行

**Comment by haixiangyan** [comment]
我查了一上，发现是 `webpack-cli` 下的 `node_modules/@webpack-cli/serve` 的版本有问题，[详见这个 Issue](https://github.com/vaadin/flow/issues/13952#issuecomment-1153616803)。

你用的是 `1.7.0`，我的 `package-lock.json` 里用的是 `1.6.1`，所以我的是OK的，你的会报错。这个版本的问题是有点坑。

解决方法是在 `package-lock.json` 里找到 `node_modules/@webpack-cli/serve` 配置项，把里面的 `"version": "1.7.0"` 改成 `"version": "1.6.1"` 即可。

我会在文档里添加这个报错的提示，感谢~
